### ISSUE TITLE
Gradually deprecate `@grafana/experimental` and move components to other UI components packages

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana-experimental#117]
Based on the discussion in https://docs.google.com/document/d/13b5_d5unZeDfNXmo6BfhORM_pOdb-NXyv2H-hJAABV0/edit?usp=sharing , we have decided to adopt a proposal to relocate stable components to other UI packages that already exist. 

# Task list
- [x] Add to README to this repository information about on-going work to move components to `@grafana/plugin-ui` and `@grafana/ui`. @gwdawson 
- [x] Review components in @grafana/experimental that can be moved to `@grafana/ui` and bring up with frontend team https://docs.google.com/spreadsheets/d/1MAR-VPDtiwbDd4wIM4WADiDdKnf21Za-_aMlnlyvqJk/edit#gid=0 @idastambuk
  - [ ] Check with frontend platform about Query Editor components
  - [ ] Possibly, write tests/documentation for untested components  
  - [ ] Possibly write stories for components
- [ ] Move LLM code to a separate repository - ask LLM team about time line @gwdawson 
  - [ ] LLM team working on this, but has some blockers 
- [x] Agree on is sql editor components are going to be moved to `@grafana/plugin-ui` - YES @gwdawson 

Lower priority/nice to have
- [ ] Visual query editor tests @ivanahuckova 
- [ ] Query editor test @idastambuk 
- [ ] SQL editor @gwdawson 

## After G11 is released
- [ ] Check what is the minimal Grafana version that all data source plugins should support @idastambuk @gwdawson 
- [ ] Check what minimal Grafana version do grafana data sources support
- [ ] Bump grafana packages version to that version in plugins-ui
- [ ] Bump dependencies
- [ ] Update plugins that need have minimal support and bundle with @grafana/ui. @scottlepp 
- [ ] Improve `@grafana/plugin-ui` and set up in the same way as we have set up experimental
- [ ] We need to wait until Grafana 11 is released and plugins support at least v 10.2 where bundling of @grafana/ui is enabled

**Comment by itsgareth** [comment]
closing because we haven't been keeping this up to date, instead we've been using the todo section in the design doc.
